config/routes.rb
Rails.application.routes.draw do
  devise_for :users,:controllers => {
    omniauth_callbacks: 'users/omniauth_callbacks',
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords'
  }
  get 'images/create'
  root "items#index"
  get 'card/new'
  get 'card/show'
  resources :users, only:[:show]
  resources :categories, only: [:index, :show, :new, :edit, :destroy]
  resources :adresses
  resources :items do
    resources :comments, only: [:new, :create]
    collection do
      get 'get_size_children', defaults: { format: 'json' }
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'search'
    end
    member do
      get 'get_size_children_edit', defaults: { format: 'json' }
      get 'get_category_children_edit', defaults: { format: 'json' }
      get 'get_category_grandchildren_edit', defaults: { format: 'json' }
    end
    resources :images, only: :create
    patch  :buy,      on: :member
    get  :comfirm,      on: :member
    get  :transaction,      on: :member
    resource :likes, only:[:create,:destroy,:show]
    end
  
  resources :adresses
  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end
  namespace :api do
    resources "destroy", controller: :items, only: :image_destroy, defaults: { format: 'json' } do
      collection do
        delete "image_destroy"
      end
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

         has_many :sns_credentials

  validates :nickname, presence: true, length: { maximum: 6 }
  validates :family_name        , presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/ }
  validates :first_name         , presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/ }
  validates :family_name_kana   , presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :first_name_kana    , presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :birthday           , presence: true
  # validates :phonenumber  , format: { with:  /\A\d{10}$|^\d{11}\z/ }

  has_many :items
  has_many :likes
  has_many :like_items, through: :likes, source: :item 
  has_many :comments
  has_many :orders
  has_one :adress
  has_many :sns_credentials

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    # sns認証したことがあればアソシエーションで取得
    # 無ければemailでユーザー検索して取得orビルド(保存はしない)
    user = sns.user || User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
        email: auth.info.email
    )
    # userが登録済みの場合はそのままログインの処理へ行くので、ここでsnsのuser_idを更新しておく
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

  def facebook
    authorization
  end

  def google_oauth2
    authorization
  end

  def failure
    redirect_to root_path
  end

  private

  def authorization
    sns_info = User.from_omniauth(request.env["omniauth.auth"])
    @user = sns_info[:user]

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
    else
      @sns_id = sns_info[:sns].id
      render template: 'devise/registrations/new'
    end
  end

end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    if params[:sns_auth] == 'true'
      pass = Devise.friendly_token
      params[:user][:password] = pass
      params[:user][:password_confirmation] = pass
    end
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    new_adress_path(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    new_adress_path(resource)
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @items = @user.items
    @like_items = @user.like_items.where(status: 0)
    @buyed_items = Item.where(buyer_user_id: @user.id)
    @selled_items = Item.where(seller_user_id: @user.id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def new_image(item)
    new_image = @images.find_by(item_id: item.id)
  end

  def like_item_image(item)
    @image = Image.find_by(item_id: item.id)
  end

  def buyed_item_image(item)
    @image = Image.find_by(item_id: item.id)
  end

end

app/views/users/show.html.haml
-if !user_signed_in? 
  = render partial:"items/header1" 
-else
  = render partial:"items/header2"
.pan
  - breadcrumb :mypage
  = breadcrumbs pretext: "現在のページ：",separator: " &rsaquo; "
.container
  .l-side
    %nav.mypage-nav
      %ul.mypage-nav-list
        %li.side_li
          =link_to "トップページ","/",class: "side_a"
        %li.side_li
          =link_to "クレジット登録","/card/new",class: "side_a"
        %li.side_li
          %p.side_b.buyed-btn 購入済み
        %li.side_li
          %p.side_b.selled-btn 出品済み
        %li.side_li
          %p.side_b.like-btn いいね一覧
  .l-content
    %section.mypage-user-icon
      .usericon
        %figure
          =image_tag("/usericon.png",class:"icon_img")
        %h2.bold
          = current_user.nickname
        .mypage-number
          .hyouka
            評価
            %span.bold
            0  
          .show_items
            出品数
            %span.bold
            0
    .mypage-tab-container-notification-todo
      .mypage-contents-main.like-main.open
        .mypage-contents-title
          %h1.like
            いいね!一覧
        .mypage-contents-box
          - @like_items.each do |item|
            .mypage-contents-box-show
              .mypage-contents-box-show-image
                = image_tag like_item_image(item).image.url , class: :img_show
              .mypage-contents-box-body
                .mypage-contents-box-body-name
                  =item.name
                .mypage-contents-box-body-price
                  =number_to_currency(item.price)
              .mypage-contents-box-icon
                =link_to item_path(item.id) do
                  %i.fas.fa-angle-right

      .mypage-contents-main.buyed-main
        .mypage-contents-title
          %h1.like
            購入済み一覧
        .mypage-contents-box
          - @buyed_items.each do |item|
            .mypage-contents-box-show
              .mypage-contents-box-show-image
                = image_tag buyed_item_image(item).image.url , class: :img_show
              .mypage-contents-box-body
                .mypage-contents-box-body-name
                  =item.name
                .mypage-contents-box-body-price
                  =number_to_currency(item.price)
              .mypage-contents-box-icon
                =link_to item_path(item.id) do
                  %i.fas.fa-angle-right

      .mypage-contents-main.selled-main
        .mypage-contents-title
          %h1.like
            出品済み一覧
        .mypage-contents-box
          - @selled_items.each do |item|
            .mypage-contents-box-show
              .mypage-contents-box-show-image
                = image_tag buyed_item_image(item).image.url , class: :img_show
              .mypage-contents-box-body
                .mypage-contents-box-body-name
                  =item.name
                .mypage-contents-box-body-price
                  =number_to_currency(item.price)
              .mypage-contents-box-icon
                =link_to item_path(item.id) do
                  %i.fas.fa-angle-right


= render partial:"items/appBanner"
= render partial:"items/footer"
=link_to "/items/new",class:"purchase" do
  .purchaseBtn
    %span.purchaseBtn__text
      出品する
    = image_tag("/icon_camera.png",class:"purchaseBtn__icon")