config/routes.rb
Rails.application.routes.draw do
  devise_for :users,:controllers => {
    omniauth_callbacks: 'users/omniauth_callbacks',
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords'
  }
  get 'images/create'
  root "items#index"
  get 'card/new'
  get 'card/show'
  resources :users, only:[:show]
  resources :categories, only: [:index, :show, :new, :edit, :destroy]
  resources :adresses
  resources :items do
    resources :comments, only: [:new, :create]
    collection do
      get 'get_size_children', defaults: { format: 'json' }
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'search'
    end
    member do
      get 'get_size_children_edit', defaults: { format: 'json' }
      get 'get_category_children_edit', defaults: { format: 'json' }
      get 'get_category_grandchildren_edit', defaults: { format: 'json' }
    end
    resources :images, only: :create
    patch  :buy,      on: :member
    get  :comfirm,      on: :member
    get  :transaction,      on: :member
    resource :likes, only:[:create,:destroy,:show]
    end
  
  resources :adresses
  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end
  namespace :api do
    resources "destroy", controller: :items, only: :image_destroy, defaults: { format: 'json' } do
      collection do
        delete "image_destroy"
      end
    end
  end

end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :explain, presence: true, length: { maximum: 1000 }
  validates :status, presence: true
  validates :condition, presence: true
  validates :shipping_fee, presence: true
  validates :shipping_days, presence: true
  validates :shipping_region, presence: true
  validates :price, presence: true, length: { maximum: 6 ,minimum: 3}
  validates :seller_user_id, presence: true
  validates :category_id, presence: true
  validates :brand, presence: true, length: { maximum: 15 }
  validates :size_id, presence: true
 

  has_many :comments
  has_many :users
  has_many :likes
  has_many :images, dependent: :destroy
  belongs_to :category
  belongs_to :size

  def self.search(search)
    return Item.all unless search
    Item.where('name LIKE(?)', "%#{search}%")
  end

  accepts_nested_attributes_for :images, allow_destroy: true
  
  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
   belongs_to_active_hash :prefecture

end

app/controllers/api/items_controller.rb
class Api::ItemsController < ApplicationController

  def image_destroy
    image = Image.find(params[:img_id])
    image.destroy
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :redirect_root, except: [:index, :show]
  before_action :set_item, only: [:buy, :show,:comfirm,:transaction,:update]

  before_action :set_image, only: [:show,:comfirm,:transaction]
  before_action :set_card, only: [:comfirm,:buy]
  before_action :set_adress, only: [:comfirm,:buy]
  


  def index
    @new_items = Item.where(status: 0).order(created_at: "desc").limit(3)
    @images = Image.all
  end

  def new
    @item = Item.new
    10.times{@item.images.build}
    @item_condition = [["新品、未使用","0"],["未使用に近い","1"],["目立った傷や汚れなし","2"],["やや傷や汚れあり","3"],["傷や汚れあり","4"],["全体的に状態が悪い","5"]]
    @item_shipping_fee = ["送料込み(出品者負担)","着払い(購入者負担)"]
    @results = Country.where('prefecture_id IN(?)', params[:prefecture_id])
    @item_shipping_days = ["1~2日で発送","2~3日で発送","4~7日で発送"]
    #データベースから、親カテゴリーのみ抽出し、配列化
    @category_parent_array = Category.where(ancestry: nil).pluck(:name,:id)
    @size_parent_array = Size.where(ancestry: nil).pluck(:size,:id)
  end

  def edit
    @item = Item.find(params[:id])
    # @item = Item.where("id = ?", 0)
    10.times{@item.images.build}
    @item_condition = [["新品、未使用","0"],["未使用に近い","1"],["目立った傷や汚れなし","2"],["やや傷や汚れあり","3"],["傷や汚れあり","4"],["全体的に状態が悪い","5"]]
    #データベースから、親カテゴリーのみ抽出し、配列化
    @category_parent_array = Category.where(ancestry: nil).pluck(:name,:id)
    @size_parent_array = Size.where(ancestry: nil).pluck(:size,:id)
    @item_status = [0,1,2,3,4]
    @item_shipping_fee = ["送料込み(出品者負担)","着払い(購入者負担)"]
    @item_shipping_days = ["1~2日で発送","2~3日で発送","4~7日で発送"]
    @images = Image.where(item_id: @item.id)
    @size = Size.find_by(id: @item.size_id)
    @size_parent = Size.find_by(id: @item.size_id).parent
    @size_children_array = Size.find_by(id: @size_parent.id).children.pluck(:size,:id)
    @selected_category = Category.find_by(id: @item.category)
    @selected_category_children = Category.find_by(id: @item.category).parent
    @category_grandchildren_array = Category.find_by(id: @selected_category_children).children.pluck(:name,:id)
    @selected_category_parent = Category.find_by(id: @item.category).root 
    @category_children_array = Category.find_by(id: @selected_category_parent).children.pluck(:name,:id)
  end

  def get_category_children
    #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    @category_children = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children
  end

  # 子カテゴリーが選択された後に動くアクション
  def get_category_grandchildren
    #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  def get_category_children_edit
    #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    @category_children = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children
  end

  # 子カテゴリーが選択された後に動くアクション
  def get_category_grandchildren_edit
    #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  def get_size_children
    #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    @size_children = Size.find_by(size: "#{params[:parent_size]}", ancestry: nil).children
  end

  def get_size_children_edit
    #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    @size_children = Size.find_by(size: "#{params[:parent_size]}", ancestry: nil).children
  end

  def get_size
    selected_grandchild = Category.find("#{params[:grandchild_id]}") #孫カテゴリーを取得
    if related_size_parent = selected_grandchild.products_sizes[0] #孫カテゴリーと紐付くサイズ（親）があれば取得
       @sizes = related_size_parent.children #紐づいたサイズ（親）の子供の配列を取得
    else
       selected_child = Category.find("#{params[:grandchild_id]}").parent #孫カテゴリーの親を取得
       if related_size_parent = selected_child.products_sizes[0] #孫カテゴリーの親と紐付くサイズ（親）があれば取得
          @sizes = related_size_parent.children #紐づいたサイズ（親）の子供の配列を取得
       end
    end
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      flash[:notice] = "出品に失敗しました"
      redirect_to new_item_path
    end
  end



  def update
    if @item.update(item_update_params) && params.require(:item).keys[0] == "images_attributes"
      redirect_to item_path(@item.id), notice: '変更内容を保存しました。'
    else
      #updateを失敗すると編集ページへ
      redirect_to edit_item_path
    end
  end



  def show
    @seller_user = User.find_by(id: @item.seller_user_id)
    @images = Image.where(item_id: @item.id)
    @results = Country.where('prefecture_id IN(?)', params[:prefecture_name])
    @size = Size.find_by(id: @item.size_id)
    @categories = Category.find_by(id:@item.category_id)
    @country = Country.create(prefecture_id:@item.shipping_region)
    @comment = Comment.new
    @comments = @item.comments.includes(:user)
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy
    redirect_to user_path(current_user.id)
  end
  
  def comfirm
    if @card
      card = Card.where(user_id: current_user.id).first
      Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end

  def buy
    @item.status = 3
    @item.buyer_user_id = current_user.id
    @item.save!(validate: false)
    Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
    charge = Payjp::Charge.create(
      amount: @item.price,
      customer: @card.customer_id, #顧客ID
      card: params['payjp-token'],
      currency: 'jpy'
    )
    redirect_to action: "transaction"
  end
  
  def transaction
    @size = Size.find_by(id: @item.size_id)
  end


  def search
    respond_to do |format|
      format.html
      format.json do
       @children = Category.find(params[:parent_id]).children
       #親ボックスのidから子ボックスのidの配列を作成してインスタンス変数で定義
      end
    end
    @items = Item.search(params[:keyword])
  end


  private
  def item_params
    params.require(:item).permit(:name,:explain,:brand,:status,:condition,:shipping_fee,:shipping_days,:shipping_region,:price,:size,:category_id,images_attributes:[:image]).merge(seller_user_id: current_user.id).merge(size_id: params[:size]).merge(category_id: params[:category_id])
  end

  def item_update_params
    params.require(:item).permit(:name,:explain,:brand,:status,:condition,:shipping_fee,:shipping_days,:shipping_region,:price,:size,:category_id,images_attributes:[:image,:id]).merge(seller_user_id: current_user.id).merge(size_id: params[:size]).merge(category_id: params[:category_id])
  end

  def redirect_root
    redirect_to root_path unless user_signed_in?
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def set_image
    @first_image = Image.find_by(item_id: @item.id)
  end

  def set_card
    @card = Card.find_by(user_id: current_user.id)
  end

  def set_adress
    @adress = Adress.find_by(user_id: current_user.id)
  end

end

app/helpers/items_helper.rb
module ItemsHelper



  def condition
    if @item.condition == 0
      condition = "新品・未使用"
    elsif @item.condition == 1
      condition = "未使用に近い"
    elsif @item.condition == 2
      condition = "目立った傷や汚れなし"
    elsif @item.condition == 3
      condition = "やや傷や汚れあり"
    elsif @item.condition == 4
      condition = "傷や汚れあり"
    elsif @item.condition == 5
      condition = "全体的に状態が悪い"
    end
  end

  def shipping_fee
    if @item.shipping_fee == 0
      shipping_fee = "送料込み"
    elsif @item.shipping_fee == 1
      shipping_fee = "送料別"
    end
  end

  def shipping_company
    if @item.shipping_company == 0
      shipping_company = "未定"
    elsif @item.shipping_company == 1
      shipping_company = "クロネコヤマト"
    elsif @item.shipping_company == 2
      shipping_company = "ゆうパック"
    elsif @item.shipping_company == 3
      shipping_company = "ゆうメール"
    end
  end

  def size
  end

  def shipping_days
    if @item.shipping_days == 0
      shipping_days = "１〜２日"
    elsif @item.shipping_days == 1
      shipping_days = "２〜３日"
    elsif @item.shipping_days == 2
      shipping_days = "４〜７日"
    end
  end

  def transaction_message_for_buyer
    if @item.status == 3
      transaction_message_for_buyer = "商品を購入しました発送までお待ちください"
    elsif @item.status == 4
      transaction_message_for_buyer = "商品が発送されました"
    elsif @item.status == 5
      transaction_message_for_buyer = "取引完了"
    end
  end

  def transaction_message_for_seller
    if @item.status == 3
      transaction_message_for_seller = "商品が購入されました。発送をお願いします"
    elsif @item.status == 4
      transaction_message_for_seller = "商品を発送しました"
    elsif @item.status == 5
      transaction_message_for_seller = "取引完了"
    end
  end


end

app/views/items/_edit-btm.html.haml
.edit-box
  .edit-box__edit-btm
    = link_to "編集する",edit_item_path(@item.id), class:"edit-btn-link"

app/views/items/_header.html.haml
!!!
%html
  %body
    %section.header
      %meta{:content => "text/html; charaset=UTF-8", "http-equiv" => "Content-Type"}/
      %title FURIMA
      %meta{:content => "authenticity_token", :name => "csrf-param"}/
      %meta{:content => "IbSlA8gY9IPjIFROBrFHKefTOqP6PjLCuGTLYiTTWixEJUwo0r+hLdG3Ys3xwXypDKHNE7dKk4rXZuPZeE2EKQ==", :name => "csrf_token"}/
      %link{:href => "items.css", :rel => "stylesheet"}/
      / cssのファイルの場所を指定
      %header.pcHeader
        .headerInner
          .mainHeader
            %h1.mainHeader_icon
              %a{:haef => "/"}
                %img.image_size_m{:src => "/logo.png"}/
                / HURIMAアイコン
            .searchBox
              %form.from_a{"accept-charset" => "UTF-8", :action => "#", :method => "get"}
                %input{:name => "utf8", :type => "hidden", :value => "✓"}/
                %input#searchInput.searchBox--input{:name => "key", :placeholder => "キーワードから探す"}/
                %button{:type => "submit"}
                  .searchBox__icon
                    %img.img_b{:src => "icon-search 1.png"}/
                / <input type="hiden" name="authenticity_token" value="get">
            %ul.resltLists
          .nav
            %ul.listsleft
              %li.listsleft__item.listsleft__item--first
                #catBtn.btm_a{:href => "#"} カテゴリー
                .tree.displayNone
                  %li.listsLeft__item
                    #brandBtn.btm_a{:href => "#"} ブランド
                    %ul.brandsPulldown.displayNone
                  %ul.listsRight
                    %li.listsRight__item.listsRight__item--login
                      = link_to "ログイン", new_user_session_path, class: "btm_a"
                    %li.listsRight__item.listsRight__item--new
                      = link_to "新規会員登録", new_user_registration_path, class: "btm_a"

app/views/items/_mainvisual-bottom.html.haml
.topKeyFeatures
  %h2.head
    FURIMAの特徴
    .under-line
  .items
    .items__section-item
      %img.top-icon{src: "/icon-01.png"}/
      %h3.item__subtitle 簡単に売り買いできる
      %p.item__detail
        スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
    .items__section-item
      %img.top-icon{src: "/icon-03.png"}/
      %h3.item__subtitle 売上金は即日振り込みに対応
      %p.item__detail
        午前９時までに振込を依頼いただければ、翌日に指定の講座に入金いたします！
    .items__section-item
      %img.top-icon{src: "/icon-04.png"}/
      %h3.item__subtitle 様々な支払いに対応
      %p.item__detail
        お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。

.pickupCountainer
  %h2.productHead
    ピックアップカテゴリー
  %h2.productHead__new-item
    = link_to '新規投稿商品', '#', class: "new-items-link"
  .productLists
    - @new_items.zip(@new_images) do |item,image|
      .productList
        .productList-img
          %img.new-item{src: "#{image.image}"}/
        .produstList-body
          .productList-body-detail
          %ul
            %li.item
              =item.name
            %li.item
              ="#{item.price}円"
            %li.item （税込）
          .productList-body-like

app/views/items/_pickupContainer.html.haml
-# 全ての商品一覧から最新を表示している
.pickupContainer
  %h2.productHead
    ピックアップカテゴリー
  %h2.productHead__new-item
    = link_to '新規投稿商品', '#', class: "new-item-link"
  .productLists
    - @new_items.each do |item|
      .productList
        =link_to item_path(item.id), class: "item-card-link" do
          .productList-img
            =image_tag "#{new_image(item).image}", class: "new-item"
          .productList-body
            %h2.item-title
              =item.name
            .productList-body__detail
              %ul
                %li.item
                  = number_to_currency(item.price)
                %li.item (税込)
              .productList-body__like
                %p 0
                %p.like-star ★

.pickupContainer
  %h2.productHead
    ピックアップブランド
  %h2.productHead__new-item
    = link_to 'アーカイバ', '#', class: "new-item-link"
  .productLists
    - @new_items.each do |item|
      .productList
        =link_to item_path(item.id), class: "item-card-link" do
          .productList-img
            =image_tag "#{new_image(item).image}", class: "new-item"
          .productList-body
            %h2.item-title
              =item.name
            .productList-body__detail
              %ul
                %li.item
                  = number_to_currency(item.price)
                %li.item (税込)
              .productList-body__like
                %p 0
                %p.like-star ★

app/views/items/_show-buybtm.html.haml
= link_to comfirm_item_path do
  .item-btn-box
    .item-btn-box__buy-btm
      購入画面に進む
-# .item-button-container
-#   %button.item-button-left.item-button-like.item-button
-#     いいね！
-#   %button.item-button-right.item-button-like.item-button
-#     不適切な商品の報告
  

app/views/items/_topKeyFeatures.html.haml
.topKeyFeatures
  %h2.head
    FURIMAの特徴
    .under-line
  .items
    .items__section-item
      =image_tag "/icon-01.png", class: "top-icon"
      %h3.item__subtitle 簡単に売り買いできる
      %p.item__detail
        スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
    .items__section-item
      =image_tag "/icon-03.png", class: "top-icon"
      %h3.item__subtitle 売上金は即日振り込みに対応
      %p.item__detail
        午前９時までに振込を依頼いただければ、翌日に指定の講座に入金いたします！
    .items__section-item
      =image_tag "/icon-04.png", class: "top-icon"
      %h3.item__subtitle 様々な支払いに対応
      %p.item__detail
        お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。

app/views/items/_topmiddledl.html.haml
%section.topMiddleDl
  .topMiddleDl__inner
    %h2.top-subtitle
      会員数日本一位
    %p.text
      FURIMAは、フリマアプリで最も人気。
      %br
      出品・購入回数も業界最多です！
      %br
      ほしかったあの商品に出会えるかもしれません。
    .content_btn
      = link_to image_tag('http://furima.tokyo/assets/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg'), '#',class: "Btn"
      = link_to image_tag('http://furima.tokyo/assets/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg'), '#',class: "Btn"

app/views/items/comfirm.html.haml
.single-container
  .single-header
    = link_to root_path, class: "header_title_a" do
      =image_tag "/logo.png", class:"header_img"
  .single-main
    %section.l-single-container
      %h2.l-single-head
        購入内容の確認
      %section.buy-content_buy-item
        .buy-content-inner
          .buy-item-image
            =image_tag "#{@first_image.image}", class: "order_img"
          .buy-item-detail
            %p.buy-item-name
              = @item.name
            %p.buy-price-ja
              %span
                = number_to_currency(@item.price)
              %span.item-shipping-fee
                = shipping_fee
      %section.buy-content_buy-item2
        .price
          %h3.cost
            支払い金額
          %p.order_price
            = number_to_currency(@item.price)
        .pay
          %h3.how
            支払い方法
          - if !@card
            = link_to new_card_path do
              登録してください
          - else
            %p.card_info
              = "**** **** **** " + @default_card_information.last4
              %br
                - exp_month = @default_card_information.exp_month.to_s
                - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
                = exp_month + " / " + exp_year      
        .adress
          %h3.send
            配送先
          .adress_info
            - if !@adress
              = link_to new_adress_path do
                登録してください
            - else
              %span 〒
              %span.adress_postal_code
                =@adress.postal_code.to_s.insert(3, "-")
              %p.adress_top
                =@adress.prefecture
                =@adress.town
              %p.adress_middle
                =@adress.number
              %p.adress_bottom
                =@adress.name
        .buy
          - if @adress  && @card
            = button_to '購入する', buy_item_path(params[:id]),method: :patch , class:"buy_btn"
          - else

  .single-footer
    %nav.list
      %ul.s
        %li.s
          プライバシーポリシー
        %li.s
          メルカリ利用規約
        %li.s
          特定商取引に関する表記
        %p.furima_logo
          ©️FURIMA

app/views/items/edit.html.haml
.newwrapper
  =form_for @item do |f|
    .newtitle
      = image_tag("/logo.png", id:"session--header--icon", class: "newtitle")
    .newpagemain
      .singlehead
        商品の情報を入力
      .sellform
        .sell-upload-box
          .upload-box-header
            = f.label :image, "出品画像"
            %span.require 必須
            %p.upbtext 最大5枚までアップロードできます
          .sell-upload-box-drop2
            %ul.sell__image-select__ul
              - @item.images.first(5).each_with_index do |image, i|
                %label{class: "sell__image-select__ul-text ul-id-#{i}"}
                  = f.fields_for :images, image do |img|
                    = img.file_field :image,"data-id": "#{i}",class: "input-area"
                    %li
                      -if image.id.present?
                        = image_tag "#{img.object.image}",size: "100x116",class:"product_image"
                    .btn-box
                      %a{ class: "delete-btn", "data-imgid": "#{image.id}" }削除
            -#           #image-box-1
            -# .item-num-0#image-box__container
            -#   = f.fields_for :images do |i|
            -#     .input-area
            -#       = i.file_field :image, type: 'file', name: "item[images_attributes][][image]", value:"", style: "display:none", id:"img-file"
      .sellcontent1
        .sellcontentwrapper1
          .content-title1
            商品名
            %span.require 必須
            = f.text_field :name, class:"content-text1", placeholder: "商品名 (必須40文字まで)", type: "text"
        .sellcontentwrapper2
          .content-title2
            商品の説明
            %span.require 必須
            =f.text_field :explain, class:"content-text2", placeholder: "商品の説明（必須1,000文字以内）（色、素材、重さ、定価、注意点など)", type: "textarea"
      .sellcontent-explain
        .sellcontent-explain-left
          %p.sellcontent-explain-left-title
            商品の詳細
        .listing-form-box
          .listing-product-detail__category
            = f.label 'カテゴリー', class: 'listing-default__label'
            %span.require 必須
            .listing-select-wrapper
              .listing-select-wrapper__box
                =f.select :category_id, @category_parent_array, {selected: @selected_category_parent.id}, {class: 'listing-select-wrapper__box--select', id: 'parent_category_edit' , name:""}

                .listing-select-wrapper__added#children_wrapper_edit
                  .listing-select-wrapper__box
                    =f.select :category_id, @category_children_array, ({selected: @selected_category_children.id, data:{category: @selected_category_children.id}}), {class: 'listing-select-wrapper__box--select', id: 'child_category_edit' , name:""}
                .listing-select-wrapper__added#grandchildren_wrapper_edit
                  .listing-select-wrapper__box 
                    =f.select :category_id, @category_grandchildren_array, {selected: @selected_category.id}, {class: 'listing-select-wrapper__box--select', id: 'grandchild_category_edit' , name:"category_id"}

          %p.sellcontent-explain-status
            ブランド
            %span.require 必須
          =f.text_field :brand, class:"content-text3", placeholder: "ブランド名 (必須15文字まで)", type: "text"
          %p.sellcontent-explain-status
            商品の状態
            %span.require 必須
          =f.hidden_field :status, :value => 0
          =f.select :condition, @item_condition,{selected: @size_parent.id},{class: "content-explain3"}
          .listing-product-detail__size
            %p.sellcontent-explain-status
              サイズ
            =f.select :size_id, @size_parent_array, {selected: @size_parent.id}, {class: 'listing-select-wrapper__box--select', id: 'parent_size_edit' , name:""}
            .listing-select-wrapper__added#children_wrapper_edit
              .listing-select-wrapper__box
                =f.select :size_id, @size_children_array, {selected: @size.id}, {class: 'listing-select-wrapper__box--select', id: 'child_size_edit' , name:"size"}
      .sellcontent-shipping 
        .sellcontent-shipping-left
          %p.sellcontent-shipping-left-title
            配送について
            %span.hatenabtn 
        .sellcontent-shipping-right 
          .sellcontent-shipping-hutan
            %p.sellcontent-shipping-hutan-title
              配送料の負担
              %span.require 必須
            =f.select :shipping_fee, @item_shipping_fee,{},{class:"content-hutan"} 
          .sellcontent-shipping-region
            %p.sellcontent-shipping-region-title
              発送元の地域
              %span.require 必須
            =f.collection_select :shipping_region, Prefecture.all,:id,:name,{},{class:"content-region "}  
          .sellcontent-shipping-days  
            %p.sellcontent-shipping-days-title
              発送までの日数
              %span.require 必須
            =f.select :shipping_days, @item_shipping_days,{},{class:"content-days"}
      .sellcontent-price
        .sellcontent-price-left
          %p.sellcontent-price-left-title
            販売価格(300~9,999,999)
            %span.hatenabtn 
        .sellcontent-price-right
          .sellcontent-price-pricebox
            %p.sellcontent-price-pricebox-title
              価格
              %span.require 必須
            =f.text_field :price,{class:"contentpricebox",placeholder: "¥"} 
          .sellcontent-price-feebox
            %p.sellcontent-price-feebox-title
              販売手数料(10%)
          .sellcontent-price-profitbox
            %p.sellcontent-price-profitbox-title
              販売利益
      .sellcontent-last
        .sellcontent-last-in
          %p.kiyaku
          禁止されている出品、行為を必ずご確認ください。
          %br
          %p.kiyaku
          またブランド品でシリアルナンバー等がある場合はご記載ください。偽ブランドの販売は犯罪であり処罰される可能性があります。
          %br
          %p.kiyaku
          また、出品をもちまして加盟店規約に同意したことになります。
          .sellcontent-last-in-btns
            =f.submit "出品する", class:"inputbtn"
            %button.inputbtnreturn 戻る
    .new-footer
      .new-footer-first
        %ul
          %li.new-footer-firsts
            プライバシーポリシー  
          %li.new-footer-firsts
            フリマ利用規約
          %li.new-footer-firsts
            特定商取引に関する表記
      .new-footer-second
        = image_tag "/logo-white.png", class: "FURIMA_img_footer-new"

app/views/items/index.html.haml
-if !user_signed_in? 
  = render partial:"header1" 
-else
  = render partial:"header2"
.main
  = render partial: "mainvisual"
  = render partial: "session-modal1"
  = render partial: "session-modal2"
  = render partial: "topintroduction"
  = render partial: "topmiddledl"
  = render partial: "topKeyFeatures"
  = render partial: "pickupContainer"
= render partial:"appBanner"
= render partial:"footer"

=link_to "/items/new", class:"purchase" do
  .purchaseBtn
    %span.purchaseBtn__text
      出品する
    =image_tag "/icon_camera.png", class:"purchaseBtn__icon"

app/views/items/search.html.haml
- if user_signed_in?
  = render partial: "header2"
- else
  = render partial: "header1"
-if @items.length >= 1
  .likes_main_title2
    %h2.searchs
      こちらのアイテムが検索されました
  .mypage-tab-container-notification-todo2
    .likes_main_box
      - @items.each do |item|
        .likes_main_box_show
          .likes_main_box_show_img
            = image_tag like_item_image(item).image.url , class: :img_show
          .likes_main_box_show_body
            .likes_main_box_show_body_name
              =item.name
            .likes_main_box_show_body_price
              #{item.price}円
          .like_icon
            =link_to item_path(item.id) do
              %i.fas.fa-angle-right
-else
  .likes_main_title2
    %h2.searchs
      お探しのアイテムは見つかりません
  .mypage-tab-container-notification-todo2
= render partial:"appBanner"
= render partial:"footer"