config/routes.rb
Rails.application.routes.draw do
  devise_for :users,:controllers => {
    omniauth_callbacks: 'users/omniauth_callbacks',
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords'
  }
  get 'images/create'
  root "items#index"
  get 'card/new'
  get 'card/show'
  resources :users, only:[:show]
  resources :categories, only: [:index, :show, :new, :edit, :destroy]
  resources :adresses
  resources :items do
    resources :comments, only: [:new, :create]
    collection do
      get 'get_size_children', defaults: { format: 'json' }
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'search'
    end
    member do
      get 'get_size_children_edit', defaults: { format: 'json' }
      get 'get_category_children_edit', defaults: { format: 'json' }
      get 'get_category_grandchildren_edit', defaults: { format: 'json' }
    end
    resources :images, only: :create
    patch  :buy,      on: :member
    get  :comfirm,      on: :member
    get  :transaction,      on: :member
    resource :likes, only:[:create,:destroy,:show]
    end
  
  resources :adresses
  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end
  namespace :api do
    resources "destroy", controller: :items, only: :image_destroy, defaults: { format: 'json' } do
      collection do
        delete "image_destroy"
      end
    end
  end

end

app/models/card.rb
class Card < ApplicationRecord
end

app/controllers/card_controller.rb
class CardController < ApplicationController
  require "payjp"
  before_action :set_card, only:[:new]

  def new
    redirect_to action: "show" if @card.exists?
  end

  def pay #payjpとCardのデータベース作成を実施します。
    Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      ) #念の為metadataにuser_idを入れましたがなくてもOK
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "show"
      else
        redirect_to action: "pay"
      end
    end
  end

  def delete #PayjpとCardデータベースを削除します
    card = Card.where(user_id: current_user.id).first
    if !card.blank?
      Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to action: "new"
  end

  def show #Cardのデータpayjpに送り情報を取り出します
    card = Card.where(user_id: current_user.id).first
    if card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end
end

private
def set_card
  @card = Card.where(user_id: current_user.id)
end

app/helpers/card_helper.rb
module CardHelper
end

app/views/card/new.html.haml
.card--top
  .card--top--header
    %a.header_title_a{href: root_path}
      %img.header_img{src: "/logo.png"}
  .card--top--title
    %section.l-single-container
      %h2.l-single-head
        クレジットカード登録
.card--main
  .card--images
    %img.card--image{:src => "/visa.png"}/
    %img.card--image{:src => "/jcb.png"}/
    %img.card--image{:src => "/mastercard.png"}/
    %img.card--image{:src => "/americanexpress.png"}/
    %img.card--image{:src => "/dinersclub.png"}/

  = form_tag(pay_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
    %label カード番号
    = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
    %br
    %label 有効期限 <br>
    %select#exp_month{name: "exp_month", type: "text"}
      %option{value: ""} --
      %option{value: "1"}01
      %option{value: "2"}02
      %option{value: "3"}03
      %option{value: "4"}04
      %option{value: "5"}05
      %option{value: "6"}06
      %option{value: "7"}07
      %option{value: "8"}08
      %option{value: "9"}09
      %option{value: "10"}10
      %option{value: "11"}11
      %option{value: "12"}12
    %span 月/
    %select#exp_year{name: "exp_year", type: "text"}
      %option{value: ""} --
      %option{value: "2020"}20
      %option{value: "2021"}21
      %option{value: "2022"}22
      %option{value: "2023"}23
      %option{value: "2024"}24
      %option{value: "2025"}25
      %option{value: "2026"}26
      %option{value: "2027"}27
      %option{value: "2028"}28
      %option{value: "2029"}29
      %option{value: "2030"}30
    %span 年
    %br
    %label セキュリティコード<br>
    = text_field_tag "cvc", "", class: "cvc", placeholder: "カード裏側の3~4桁の番号", maxlength: "4", id: "cvc"
    #card_token
    = submit_tag "登録する", id: "token_submit"


    <br>test : 4242424242424242

app/views/card/show.html.haml
.card--top
  .card--top--header
    %a.header_title_a{href: root_path}
      %img.header_img{src: "/logo.png"}
  .card--top--title
    %section.l-single-container
      %h2.l-single-head
        クレジットカード情報確認画面
.card--main
  .card--images
    %img.card--image{:src => "/visa.png"}/
    %img.card--image{:src => "/jcb.png"}/
    %img.card--image{:src => "/mastercard.png"}/
    %img.card--image{:src => "/americanexpress.png"}/
    %img.card--image{:src => "/dinersclub.png"}/
  %label.card-name 登録クレジットカード情報
  .test222
    %br
      = "**** **** **** " + @default_card_information.last4
    %br
    - exp_month = @default_card_information.exp_month.to_s
    - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
    = exp_month + " / " + exp_year
    = form_tag(delete_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
      %input{ type: "hidden", name: "card_id", value: "" }
      %button 削除する
      =link_to 'ホームへ戻る', root_path