config/routes.rb
Rails.application.routes.draw do
  devise_for :users,:controllers => {
    omniauth_callbacks: 'users/omniauth_callbacks',
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords'
  }
  get 'images/create'
  root "items#index"
  get 'card/new'
  get 'card/show'
  resources :users, only:[:show]
  resources :categories, only: [:index, :show, :new, :edit, :destroy]
  resources :adresses
  resources :items do
    resources :comments, only: [:new, :create]
    collection do
      get 'get_size_children', defaults: { format: 'json' }
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'search'
    end
    member do
      get 'get_size_children_edit', defaults: { format: 'json' }
      get 'get_category_children_edit', defaults: { format: 'json' }
      get 'get_category_grandchildren_edit', defaults: { format: 'json' }
    end
    resources :images, only: :create
    patch  :buy,      on: :member
    get  :comfirm,      on: :member
    get  :transaction,      on: :member
    resource :likes, only:[:create,:destroy,:show]
    end
  
  resources :adresses
  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end
  namespace :api do
    resources "destroy", controller: :items, only: :image_destroy, defaults: { format: 'json' } do
      collection do
        delete "image_destroy"
      end
    end
  end

end

app/models/category.rb
class Category < ApplicationRecord
 has_many :items
 has_ancestry
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @parents  =  Category.where(ancestry: nil).limit(13) #レディース
    @parents_first = Category.where(ancestry: nil)
    
  end
    def create
      @category = @item.categories.new(category_params)
    end
  
    private
    def category_params
      params.require(:category).permit(:category)
    end

end

app/helpers/categories_helper.rb
module CategoriesHelper

  def category_aaa(parent)
    @bbb = parent.id
    @bbb += 1
    @next_parent = Category.find_by(id: @bbb)
    @ppp = @next_parent.ancestry
    @vvv = Category.where(ancestry: @ppp)
  end
  def category_bbb(parent2)
    @bbb2 = parent2.id
    @bbb2 += 2
    @next_parent2 = Category.find_by(id: @bbb2)
    @ppp2 = @next_parent2.ancestry
    @vvv2 = Category.where(ancestry: @ppp2)
  end

end

app/views/categories/_appBanner.html.haml
%section.appBanner
  .inner
    %h2.inner__title だれでもかんたん、人生を変えるフリマアプリ
    %p.inner__text 今すぐ無料ダウンロード
    .content_btn_bottom
      = link_to image_tag('http://furima.tokyo/assets/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg'), '#',class: "Btn"
      = link_to image_tag('http://furima.tokyo/assets/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg'), '#',class: "Btn"

app/views/categories/_footer.html.haml
!!!
%html
  %body
    %section.footer
      %ul.contents_footer
        %li.content_footer
          %h2.content_footer__head FUIMAについて
          %ul.b
            %li
              = link_to "会社概要（運営会社",root_path, class: "menu"
            %li
              = link_to "プライバシーポリシー",root_path, class: "menu"
            %li
              = link_to "FURIMA利用規約",root_path, class: "menu"
            %li
              = link_to "ポイントに関する特約",root_path, class: "menu"
        %li.content_footer
          %h2.content_footer__head FURIMAを見る
          %ul.b
            %li
              = link_to "会社概要（運営会社）",root_path, class: "menu"
            %li
              = link_to "プライバシーポリシー",root_path, class: "menu"
        %li.content_footer
          %h2.content_footer__head ヘルプ＆ガイド
          %ul.b
            %li
              = link_to "FURIMAガイド",root_path, class: "menu"
            %li
              = link_to "FURIMAロゴ利用ガイドライン",root_path, class: "menu"
            %li
              = link_to "お知らせ",root_path, class: "menu"
      .footer__logo
        = link_to "/" do
          = image_tag "/logo-white.png", class: "FURIMA_img_footer"
      %p © FURIMA

app/views/categories/_header1.html.haml
!!!
%html
  %body
    %section.header
      / cssのファイルの場所を指定
      %header.pcHeader
        .headerInner
          .mainHeader
            %h1.mainHeader_icon
              =link_to root_path do
                =image_tag "/logo.png", class: "image_size_m"
                / HURIMAアイコン
            .searchBox
              = form_with(url: search_items_path, local: true, method: :get, class: "from_a") do |form|
                = form.text_field :keyword, placeholder: "投稿を検索する", class: "searchBox--input",id: "searchInput" 
                %label{:for => "search_btn"}
                  .searchBox__icon
                    =image_tag "/icon-search 1.png", class:"img_b"
                    = form.submit "検索", class: "button_a2",id: "search_btn"
            %ul.resltLists
          .nav
            %ul.listsleft
              %li.listsleft__item.listsleft__item--first
                =link_to "カテゴリー" ,categories_path, class: "btm_a"
                .tree.displayNone
                  %li.listsLeft__item
                    =link_to "ブランド" ,"#", class: "btm_a"
                    %ul.brandsPulldown.displayNone
                  %ul.listsRight
                    %li.listsRight__item.listsRight__item--login
                      %p.btm_a.login-user ログイン
                    %li.listsRight__item.listsRight__item--new
                      %p.btm_a.new-user 新規会員登録         

app/views/categories/_header2.html.haml
!!!
%html
  %body
    %section.header
      / cssのファイルの場所を指定
      %header.pcHeader
        .headerInner
          .mainHeader
            %h1.mainHeader_icon
              =link_to root_path do
                =image_tag "/logo.png",class: "image_size_m"
            .searchBox
              = form_with(url: search_items_path, local: true, method: :get, class: "from_a") do |form|
                = form.text_field :keyword, placeholder: "投稿を検索する", class: "searchBox--input",id: "searchInput" 
                %label{:for => "search_btn"}
                  .searchBox__icon
                    =image_tag "/icon-search 1.png", class:"img_b"
                    = form.submit "検索", class: "button_a2",id: "search_btn"
            %ul.resltLists
          .nav
            %ul.listsleft
              %li.listsleft__item.listsleft__item--first
                =link_to "カテゴリー" ,categories_path, class: "btm_a"
                .tree.displayNone
                  %li.listsLeft__item
                    =link_to "ブランド" ,"#", class: "btm_a"
                    %ul.brandsPulldown.displayNone
                  %ul.listsRight
                    %li.listsRight__item.listsRight__item--iine
                      = link_to "いいね一覧",root_path, class: "btm_a"
                    %li.listsRight__item.listsRight__item--mypage
                      = link_to "マイページ", user_path(current_user.id), class: "btm_a"
                    %li.listsRight__item.listsRight__item--mypage
                      = link_to "ログアウト", destroy_user_session_path, class: "btm_a", method: "delete"

app/views/categories/index.html.haml
- if user_signed_in?
  = render partial: "header2"
- else
  = render partial: "header1"
  
.category_lappar
  .breadCrumbs
    .breadCrumbs.ul
      .li FURIMA
      .li.fa.fa-angle-right
        
      .li カテゴリー一覧
      .test{:onclick => "scrollToTop()"}
.category_lappar2
  .category-index.l-single-container
    .visible-sp
      .search-category
        .gray.clearfix
          カテゴリー一覧
        .category-list.btn{:onclick => "scrollTo(target)"}
          - @parents.each do |parent| 
            = link_to "#{parent.name}","#",class: "test-d"
        .category-list-nav.slide-nav-parent.text-center.clearfix
          - @parents_first.each do |parent| 
            = link_to "#{parent.name}","#",:id => "#{parent.name}",class: "test-b"
            - category_aaa(parent).each do |v|
              = link_to "#{v.name}", "#", class: "test-c"
              - category_bbb(parent).each do |v2|
                = link_to "#{v2.name}", "#", class: "test-d2122"
= render partial:"appBanner"
= render partial:"footer"